
name: Input test
on:
  workflow_dispatch
    inputs:
      run-tests:
        description: "run tests ?"
        type: boolean
        required: true
      test-type:
        description: "Type of text to run?"
        type: choice
        options:
          - unit
          - integration
          - all
        required: true  
      environment:
        description: "Select the Enviroment"
        type: environment
        required: true

      build-number:
        description: "Select buid no."
        type: number
        required: false
      message:
        description: "Select buid no."
        type: string
        required: false
 jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: print the work flow input
     run:|
       echo "Run tests: ${{ inputs.run-tests }}"
       echo "Test type: ${{ inputs.test-type }}"
       echo "Enviroment: ${{ inputs.environment }}"
       echo "Build-Number: ${{ inputs.build-number }}"
       echo "Message: ${{ inputs.Message }}"

    - name: run test (if selected)
      if: ${{inputs.run-tests == 'true'}}:
      run: echo "Testing.........."   

      
